name: Android Testing CI
on: [push, pull_request]

jobs:
  testUnitarios:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Android Tests Reports
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}